DROP TABLE FRIENDOF;
DROP TABLE FANOF;
DROP TABLE POST;
DROP TABLE ADMIRE;
DROP TABLE INTEREST;
DROP TABLE HASA;
DROP TABLE HASHTAG;
DROP TABLE MAYHAVE;
DROP TABLE COMMENT;
DROP TABLE MESSAGE;
DROP TABLE USERS;

CREATE TABLE USERS
	(
	 USERID INTEGER NOT NULL,
	 USERNAME VARCHAR(100) NOT NULL,
	 FIRSTNAME VARCHAR(50) NOT NULL,
	 LASTNAME VARCHAR(50) NOT NULL,
	 PASSWORD VARCHAR(300) NOT NULL,
	 AFFILIATION VARCHAR(100),
	 BIRTHDAY VARCHAR(50),
	 PRIMARY KEY (USERID)
	)
;

CREATE TABLE MESSAGE
	(
	 MSGID INTEGER NOT NULL,
	 SENDER INTEGER NOT NULL,
	 RECIEVER INTEGER NOT NULL,
	 MSG VARCHAR(1000),
	 PRIMARY KEY (MSGID),
	 FOREIGN KEY(SENDER) REFERENCES USERS(USERID),
	 FOREIGN KEY(RECIEVER) REFERENCES USERS(USERID)
	)
;

CREATE TABLE HASHTAG
	(
		TAGID INTEGER NOT NULL,
		TAG VARCHAR(100) NOT NULL,
		PRIMARY KEY(TAGID)
	)
;

CREATE TABLE  INTEREST
	(
		IID INTEGER NOT NULL,
		INTEREST VARCHAR(100) NOT NULL,
		PRIMARY KEY(IID)
	)
;

CREATE TABLE COMMENT
       (
	      CID INTEGER NOT NULL,
	      MSG VARCHAR(100) NOT NULL,
	      COMMENTOR INTEGER NOT NULL,
	      PRIMARY KEY(CID),
	      FOREIGN KEY (COMMENTOR) REFERENCES USERS(USERID)
	)
;

CREATE TABLE FRIENDOF
	(
		USERID INTEGER NOT NULL,
		FID INTEGER NOT NULL,
		FOREIGN KEY (USERID) REFERENCES USERS(USERID),
		FOREIGN KEY (FID) REFERENCES USERS(USERID)
	)
;

CREATE TABLE FANOF
	(
		USERID INTEGER NOT NULL,
		IID INTEGER NOT NULL,
		FOREIGN KEY (USERID) REFERENCES USERS(USERID),
		FOREIGN KEY (IID) REFERENCES INTEREST(IID)
	)
;

CREATE TABLE POST
	(
		USERID INTEGER NOT NULL,
		MSGID INTEGER NOT NULL,
		DAT VARCHAR(50),
		FOREIGN KEY (USERID) REFERENCES Users(USERID),
		FOREIGN KEY (MSGID)  REFERENCES MESSAGE(MSGID)
	)
;

CREATE TABLE HASA
	(
		MSGID INTEGER NOT NULL,
		TAGID INTEGER NOT NULL,
		FOREIGN KEY (MSGID) REFERENCES MESSAGE(MSGID),
		FOREIGN KEY (TAGID) REFERENCES HASHTAG(TAGID)
	)
;

CREATE TABLE ADMIRE
	(
		USERID INTEGER NOT NULL,
		MSGID INTEGER NOT NULL,
		FOREIGN KEY (USERID) REFERENCES USERS(USERID),
		FOREIGN KEY (MSGID) REFERENCES MESSAGE(MSGID)
	)
;

CREATE TABLE MAYHAVE
       (
               MSGID INTEGER NOT NULL,
	       CID INTEGER NOT NULL,
	       DAT VARCHAR(50),
	       FOREIGN KEY (MSGID) REFERENCES MESSAGE(MSGID),
	       FOREIGN KEY (CID) REFERENCES COMMENT(CID)
	)
;